# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11eac8c2e90066662700c511805622911bbe847e7b5b1c846448c5b04deaabf0c921337396a0b8c4d8ef2f0c8921640499bd10f1bca953ad4fe0e485ee12762f

test:
  secret_key_base: e3306da7827b613416446fce16f193779186a6c30e4930d38f4ffb259af86b16222481b5c13a8b101f3c4f91d56427d111d4a26952cc1127b0e28d9518894fdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
