# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dc01a5cb9b176f42abd216d18b40737c2c3eb4ffd577ea084001b8d84b0666f893492d97b47bbe957aa0df2afc3528c50badc9c9db5f264d58dc69d4d0b9810

test:
  secret_key_base: 75cfe7c636011b7eba96ea62842aa2a5247bef2a71368ffd748533427d5f3654b15ee97463b4c9a5c8b3d536dde8f07cca3ad54189904c3bd2b2b02450b327e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
